---
inventory_vlans:
  - name: default
    vlan_id: 1
    subnets:
      - 172.16.0.3/17
      - 172.16.1.3/17

  - name: network
    vlan_id: 2
    subnets:
      - 172.16.2.3/24

  - name: services
    vlan_id: 3
    subnets:
      - 172.16.3.3/24

  - name: personal
    vlan_id: 10
    subnets:
      - 172.16.10.3/24

  - name: developer
    vlan_id: 30
    subnets:
      - 172.16.30.3/24

  - name: automation
    vlan_id: 666
    subnets:
      - 172.16.66.3/23

  - name: IPMI
    vlan_id: 99
    subnets:
      - 172.16.99.3/24

  - name: SAN
    vlan_id: 100
    subnets:
      - 172.16.100.3/24

  - name: metal
    vlan_id: 110
    subnets:
      - 172.16.110.3/24

  - name: virtual
    vlan_id: 120
    subnets:
      - 172.16.120.3/22

  - name: ocp4
    vlan_id: 140
    subnets:
      - 172.16.140.3/22

  - name: media
    vlan_id: 247
    subnets:
      - 172.16.247.3/24

  - name: wifi
    vlan_id: 2400
    subnets:
      - 172.16.251.3/24

  - name: guest
    vlan_id: 67
    subnets:
      - 172.16.254.3/23
